services:
  - type: web
    name: line-discord-bridge
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true 